import Link from "next/link";
import { notFound } from "next/navigation";
import { ExternalLink } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ToolCard } from "@/components/tool-card";
import { FavoriteButton } from "@/components/favorite-button";
import { getAlternatives, getTool } from "@/lib/catalog";
import { tools } from "@/lib/data/tools";
export async function generateStaticParams(){ return tools.map(t=>({slug:t.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const tool=getTool(slug); return { title: tool?.name || "Tool", description: tool ? `${tool.name} pricing, advantages, disadvantages, platforms, and alternatives.` : undefined }; }
export default async function ToolPage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const tool=getTool(slug); if(!tool) notFound(); const alternatives=getAlternatives(tool.slug); return <section className="mx-auto max-w-7xl px-4 py-14"><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><div><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-primary">{tool.category} · {tool.subCategory}</p><h1 className="mt-2 text-5xl font-black">{tool.name}</h1><p className="mt-4 max-w-2xl text-muted-foreground">A curated profile of {tool.name}: pricing, best use cases, pros, cons, alternatives, platforms, and workflow fit.</p></div><FavoriteButton slug={tool.slug} name={tool.name}/></div><div className="mt-6 flex flex-wrap gap-2"><Badge>{tool.pricing}</Badge><Badge>{tool.budgetRange}</Badge><Badge>Rating {tool.rating}</Badge><Badge>{tool.aiCapabilities} AI</Badge></div><div className="mt-8 grid gap-4 md:grid-cols-2"><Card><h2 className="text-xl font-bold">Advantages</h2><ul className="mt-3 list-inside list-disc space-y-2 text-sm text-muted-foreground">{tool.advantages.map(x=><li key={x}>{x}</li>)}</ul></Card><Card><h2 className="text-xl font-bold">Disadvantages</h2><ul className="mt-3 list-inside list-disc space-y-2 text-sm text-muted-foreground">{tool.disadvantages.map(x=><li key={x}>{x}</li>)}</ul></Card></div><Card className="mt-6"><h2 className="text-xl font-bold">Tool facts</h2><dl className="mt-4 grid gap-4 md:grid-cols-2">{[["Best for",tool.bestFor.join(", ")],["Platforms",tool.platforms.join(", ")],["Ease of use",tool.easeOfUse],["Integrations",tool.integrations],["Team support",tool.teamSupport],["Free plan",tool.freePlan?"Yes":"No"]].map(([k,v])=><div key={k}><dt className="text-sm font-medium">{k}</dt><dd className="text-sm text-muted-foreground">{v}</dd></div>)}</dl></Card><div className="mt-10"><h2 className="text-2xl font-bold">Alternatives to {tool.name}</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{alternatives.map(t=><ToolCard key={t.slug} tool={t}/>)}</div></div></div><aside className="space-y-4"><Card><Button asChild className="w-full"><Link href={tool.website} target="_blank" rel="noreferrer">Visit website <ExternalLink className="h-4 w-4"/></Link></Button><Button asChild variant="outline" className="mt-3 w-full"><Link href={`/compare?tools=${tool.slug}`}>Compare</Link></Button></Card><Card><h2 className="font-bold">Tags</h2><div className="mt-3 flex flex-wrap gap-2">{tool.tags.map(tag=><Badge key={tag}>{tag}</Badge>)}</div></Card></aside></div></section> }
